### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by jfbourdon**
Adds French translation. It's the first time I'm doing this so I hope the files are right.

In doing that, I came to question two things:

- Considering my last PR (#30), does the checkbox `Display a notification once the plugin is reloaded` still needs to be present as the success notification won't appear if the plugin fails to reload ?
- _Plugin Reloader_ being the name of the plugin, should this string in `unload()` stay the same in all languages? If so, should the `self.tr()` be removed then?
https://github.com/borysiasty/plugin_reloader/blob/ccf682790193d039e2821389c4be2049e39554c4/reloader_plugin.py#L223

### CODE REVIEW

**Comment by borysiasty** [comment]
Looks good!

> does the checkbox Display a notification once the plugin is reloaded still needs to be present ?

I put that checkbox to not annoy people with too many overlapping messages. Personally I keep it enabled, but some plugins display their own messages on load, so someone may prefer to disable it. Anyway, personally I never disable it, so I won't cry if is't always on.  

> should this string in unload() stay the same in all languages?

Good question. That text is just a submenu branch in the Plugins' menu. I've no strong opinion if we should allow people to translate it or stick exactly with the plugin name. In Polish, I leaved in untouched, in German Werner translated it to `Plugin-Reloader`, what probably looks more native, still being recognizable. Anyway, if removing from translations, we would need to do the same in line 204, where that submenu is created: 

https://github.com/borysiasty/plugin_reloader/blob/ccf682790193d039e2821389c4be2049e39554c4/reloader_plugin.py#L204

The good thing is both strings are translated at once, so there is no risk to break anything by making them different.

**Comment by borysiasty** [comment]
Ok, 0.9.1 is released now. In short, I'm neither convinced to the two changes above, nor I'm strictly against them.

**Comment by jfbourdon** [comment]
I didn't thought of the case where a plugin was displaying a message on startup, it seems to me a good enough justification to keep the option.
 
With release 0.9.1, it's now time to download the plugin I'm abusing the most! Thanks!

**Comment by borysiasty** [comment]
Thanks a lot and sorry for not reading GH notifications for the 2 months! :)

**Pull request merged**
